export default {
  title: 'Odin Chart',
  actions: {
    cancel: 'Cancel',
    download: 'Download',
    duplicate: 'Make a copy',
    ok: 'OK',
    delete: 'Delete',
    save: 'Save',
    saveandclose: 'Save & close',
    saving: 'Saving',
    share: 'Share',
    update: 'Update',
    upload: 'Upload',
    create: 'Sign Up',
    submit: 'Submit',
    resetPassword: 'Send Reset Link',
  },
  header: {
    account: 'Account',
    home: 'Home',
    logOut: 'Log Out',
    plugins: 'Plugins',
  },
  footer: {
    copyright: 'Copyright {year}',
    faq: 'FAQ',
    feedback: 'Feedback',
  },
  labels: {
    rememberedPassword: 'I remembered my password!',
    alreadyHaveAccount: 'I already have an account',
    googleSignIn: 'Sign in with Google',
    twitterSignIn: 'Sign in with Twitter',
    appearance: 'Appearance',
    background: 'Background',
    bugReport: 'Bug Report',
    chartMod: 'Modification',
    close: 'Close',
    comment: 'Comment',
    confirmPassword: 'Confirm Password',
    copyShareLink: 'Copy Share Link',
    copyEmbedLink: 'Copy Embed Link',
    createOne: 'Create One',
    forgotPassword: 'Forgot password',
    dataSet: 'Data Set',
    numberType: 'Number Type',
    numberDist: 'Number Distribution',
    decimals: 'Decimals',
    deleteAccount: 'Delete Account',
    downwards: 'Downward',
    email: 'Email',
    error: 'Error',
    featureRequest: 'Feature Request',
    feedback: 'Feedback',
    signUpStatement: 'Sign up to get access to Odin Chart',
    fullName: 'Name',
    googleSheetCode: 'Google Sheet Code',
    UrlCode: 'Enter URL',
    import: 'Import',
    importFrom: 'or import from',
    info: 'Info',
    integers: 'Integers',
    password: 'Password',
    randomDataSetting: 'Random Generator Settings',
    range: 'Range',
    rangeLat: 'Latitude Range',
    rangeLng: 'Longitude Range',
    resetForm: 'Reset',
    seeMore: 'See More',
    shareChart: 'Share your chart',
    shareLink: '',
    sharedLink: 'Get Share Link',
    signIn: 'Sign In',
    signUpFormTitle: 'Sign Up Form',
    success: 'Success',
    termsStatement: 'I have read and agree to Odin Chart',
    terms: 'Terms and Conditions',
    trend: 'Trend',
    upwards: 'Upward',
    viewAll: 'View all',
    viewData: 'Manage Data',
    normallyDistributed: 'Normally Distributed',
    harmonic: 'Harmonic',
    random: 'Random',
    genRandomLabels: 'Random Labels',
    chartOptions: {
      footnote: 'Chart Footnote',
      legendSymbol: 'Legend Symbol',
      backgroundColor: 'Background Color',
      showTitle: 'Show Title',
      drawAnimation: 'Animation on load',
      innerRadius: 'Inner Radius',
      labelRadius: 'Label Radius',
      labelPie: 'Chart Label',
      lineLabels: 'Show Line Labels',
      lineWidth: 'Adjust Line Width',
      barWidth: 'Adjust Bar Width',
      symbolSize: 'Adjust Symbol Size',
      headerBorderColor: 'Header Border Color',
      headerTextColor: 'Header Text Color',
      bodyBorderColor: 'Body Border Color',
      bodyTextColor: 'Body Text Color',
      rowHighlightInterval: 'SRow Interval',
      rowHighlightColor: 'Highlight Row Color',
      legend: 'Show Legend',
      showXTickLines: 'Tick Lines',
      showYTickLines: 'Tick Lines',
      showXAxisLine: 'Axis Line',
      showYAxisLine: 'Axis Line',
      showAxes: 'Show Axes',
      showXAxisPadding: 'Label Padding',
      showYAxisPadding: 'Label Padding',
      showXGrid: 'Grid Lines',
      showYGrid: 'Grid Lines',
      showLabels: 'Show Labels on Chart',
      showHoverbox: 'Show ToolTip',
      interpolation: 'Smooth Lines',
      highlighted: 'highlighted Interval',
      nonHighlighted: 'non-highlighted Interval',
      axisLineWidth: 'Axis Line Width',
    },
    continue: 'Continue',
  },
  shapes: {
    circle: 'Circle',
    rectangle: 'Rectangle',
    triangle: 'Triangle',
    none: 'None',
  },
  messages: {
    forgotPassword: 'Enter your email below to reset your account password',
    accountCreated: 'Your account has been successfully created',
    accountUnverified: 'Your account is not verified',
    anyOneCanViewChart: 'Anyone with this link can view the chart',
    changesUptoDate: 'All changes are up to date',
    chartDeleted: 'Chart has been deleted',
    chartNotExists: "Chart doesn't exist",
    confirmDelete: 'Are you sure you want to delete?',
    confirmDeleteAccount: 'Are you sure you want to delete your account?',
    confirmLogOut: 'Are you sure you want to log out?',
    copyShareLink: 'Copy the link below to share with anyone',
    copyEmbedLink: 'Copy the link below to embed it in on your own site',
    dataImport: 'Select a source from which you want to grab your data from',
    deleteChart: 'This will permanently delete the chart. Continue?',
    chartDuplicated: 'Chart has been successfully duplicated',
    chartSaved: 'Chart has been successfully saved',
    chartUpdated: 'Chart has been successfully updated',
    chartUptoDate: 'Chart is already up to date',
    createdWith: 'This visualization was created with',
    deleteWarning:
      'If you delete your account, all data will be <b>permanently</b> removed. You will not be able to retrieve the deleted data.',
    discardUnsavedChanges: 'All unsaved changes would be lost. Continue?',
    feedbackReceived: 'We have received your feedback',
    feedbackRequest: "Your feedback makes Odin Chart better. Tell us what you're really thinking!",
    feedbackType: 'Is this a bug report or a feature request?',
    fieldRequired: 'This field is required',
    invalidUrl: 'Url is not valid',
    linkCopied: 'Link copied to clipboard',
    noData: 'No Data',
    newDataSuccess: 'Data has been successfully imported',
    noAccount: "Don't have an account?",
    passwordForDelete: 'Type your password below and click "Delete" to delete your account',
    passwordsNotMatch: 'Confirm password does not match the original one',
    termsRequired: 'Please accept terms and conditions',
    resourceNotExists: 'Resource does not exist',
    noFileSelected: 'No File Selected',
    sizeTooBig: 'File size too big',
    wrongType: 'Input File Format Incorrect',
    signUpMessage: 'Sign in to Odin Chart',
    startMakingCharts: 'Start making your own charts now',
    thankYou: 'Thank You!',
    uploadMessage: 'Drop file here or click to upload',
    uploadInstruction: 'CSV, xls or xlsx files with a size less than 500kb',
    welcomeBack: 'Welcome <b>{name}</b>',
    warning: 'Warning',
    signUpSuccessMessage: 'Congratulations! Your account is successfully created.',
    confirmationLogin: 'Please confirm your email from your mail box',
  },
  misc: {
    axisStyle: 'Axis Style',
    chartStyle: 'Chart Style',
    chartName: 'Chart Name',
    chartType: 'Chart Type',
    mapType: 'Map Type',
    createNewChart: 'Create New Chart',
    createNewColorPalette: 'Create New Palette',
    dataImport: 'Data Import Wizard',
    dateCreated: 'Date Created',
    deleteCancelled: 'Delete Cancelled',
    downloadButton: 'Download',
    downloadPNG: 'Download PNG',
    downloadSVG: 'Download SVG',
    generateRandom: 'Generate Random',
    isShared: 'Shared?',
    localSystem: 'Local',
    palette: 'Palette',
    savedCharts: 'Saved Charts',
    savedColorPalettes: 'Saved Color Palettes',
  },
  charts: {
    area: 'Area Chart',
    bar: 'Bar Chart',
    choropleth: 'Choropleth',
    dataDriven: 'Data-driven point size',
    donut: 'Donut Chart',
    fixed: 'Fixed point size',
    groupedBar: 'Grouped Bar Chart',
    horizontalBar: 'Horizontal Bar Chart',
    line: 'Line Chart',
    map: 'Map Chart',
    pie: 'Pie Chart',
    scatter: 'Scatter Chart',
    stackedArea: 'Stacked Area',
    stackedBar: 'Stacked Bar Chart',
    symbolsOnMap: 'Symbols on Map',
    table: 'Table',
    verticalBar: 'Vertical Bar Chart',
  },
  settingsSections: {
    basic: 'Basic Settings',
    composition: 'Composition',
    chartStyle: 'Chart Styles',
    titles: 'Title/Footnotes',
    legend: 'Legend',
    axis: 'Axis Style',
    annotations: 'Annotations',
    popover: 'Popover',
    mods: 'Modifications',
    general: 'General',
    xAxis: 'X axis',
    yAxis: 'Y axis',
    generalStyle: 'Styles',
  },
};
